// country-mapping.js - Mapiranje imena država na ISO kodove
// Ovaj fajl sadrži sve mappings odvojeno za bolje performanse

export const countryMapping = {
    // Evropa
    'Croatia': 'HRV',
    'Germany': 'DEU',
    'France': 'FRA',
    'Italy': 'ITA',
    'Spain': 'ESP',
    'Poland': 'POL',
    'United Kingdom': 'GBR',
    'Netherlands': 'NLD',
    'Belgium': 'BEL',
    'Switzerland': 'CHE',
    'Austria': 'AUT',
    'Sweden': 'SWE',
    'Norway': 'NOR',
    'Denmark': 'DNK',
    'Finland': 'FIN',
    'Portugal': 'PRT',
    'Greece': 'GRC',
    'Turkey': 'TUR',
    'Ukraine': 'UKR',
    'Russia': 'RUS',
    'Romania': 'ROU',
    'Bulgaria': 'BGR',
    'Hungary': 'HUN',
    'Czech Republic': 'CZE',
    'Slovakia': 'SVK',
    'Slovenia': 'SVN',
    'Bosnia and Herzegovina': 'BIH',
    'Serbia': 'SRB',
    'Montenegro': 'MNE',
    'Macedonia': 'MKD',
    'Albania': 'ALB',
    'Republic of Serbia': 'SRB',
    'Lithuania': 'LTU',
    'Latvia': 'LVA',
    'Estonia': 'EST',
    'Belarus': 'BLR',
    'Moldova': 'MDA',
    'Georgia': 'GEO',
    'Armenia': 'ARM',
    'Azerbaijan': 'AZE',
    'Iceland': 'ISL',
    'Ireland': 'IRL',
    'Luxembourg': 'LUX',
    'Malta': 'MLT',
    'Cyprus': 'CYP',
    
    // Amerika
    'United States of America': 'USA',
    'United States': 'USA',
    'USA': 'USA',
    'Canada': 'CAN',
    'Mexico': 'MEX',
    'Brazil': 'BRA',
    'Argentina': 'ARG',
    'Chile': 'CHL',
    'Colombia': 'COL',
    'Peru': 'PER',
    'Venezuela': 'VEN',
    'Ecuador': 'ECU',
    'Bolivia': 'BOL',
    'Paraguay': 'PRY',
    'Uruguay': 'URY',
    'Guatemala': 'GTM',
    'Honduras': 'HND',
    'El Salvador': 'SLV',
    'Nicaragua': 'NIC',
    'Costa Rica': 'CRI',
    'Panama': 'PAN',
    'Cuba': 'CUB',
    'Jamaica': 'JAM',
    'Haiti': 'HTI',
    'Dominican Republic': 'DOM',
    'Puerto Rico': 'PRI',
    'Guyana': 'GUY',
    'Suriname': 'SUR',
    'French Guiana': 'GUF',
    'Bahamas': 'BHS',
    
    // Azija
    'China': 'CHN',
    'Japan': 'JPN',
    'India': 'IND',
    'Pakistan': 'PAK',
    'Bangladesh': 'BGD',
    'Indonesia': 'IDN',
    'Philippines': 'PHL',
    'Vietnam': 'VNM',
    'Thailand': 'THA',
    'Myanmar': 'MMR',
    'Malaysia': 'MYS',
    'Singapore': 'SGP',
    'South Korea': 'KOR',
    'North Korea': 'PRK',
    'Mongolia': 'MNG',
    'Kazakhstan': 'KAZ',
    'Uzbekistan': 'UZB',
    'Kyrgyzstan': 'KGZ',
    'Tajikistan': 'TJK',
    'Turkmenistan': 'TKM',
    'Afghanistan': 'AFG',
    'Iran': 'IRN',
    'Iraq': 'IRQ',
    'Syria': 'SYR',
    'Lebanon': 'LBN',
    'Jordan': 'JOR',
    'Israel': 'ISR',
    'Saudi Arabia': 'SAU',
    'Yemen': 'YEM',
    'Oman': 'OMN',
    'United Arab Emirates': 'ARE',
    'Qatar': 'QAT',
    'Kuwait': 'KWT',
    'Bahrain': 'BHR',
    'Sri Lanka': 'LKA',
    'Nepal': 'NPL',
    'Bhutan': 'BTN',
    'Maldives': 'MDV',
    'Laos': 'LAO',
    'Cambodia': 'KHM',
    'Brunei': 'BRN',
    'East Timor': 'TLS',
    'Taiwan': 'TWN',
    'Hong Kong': 'HKG',
    'Macau': 'MAC',
    
    // Afrika
    'Egypt': 'EGY',
    'Libya': 'LBY',
    'Tunisia': 'TUN',
    'Algeria': 'DZA',
    'Morocco': 'MAR',
    'Sudan': 'SDN',
    'South Sudan': 'SSD',
    'Ethiopia': 'ETH',
    'Eritrea': 'ERI',
    'Djibouti': 'DJI',
    'Somalia': 'SOM',
    'Somaliland': 'SOL',
    'Kenya': 'KEN',
    'Uganda': 'UGA',
    'Tanzania': 'TZA',
    'United Republic of Tanzania': 'TZA',
    'Rwanda': 'RWA',
    'Burundi': 'BDI',
    'Democratic Republic of the Congo': 'COD',
    'Republic of the Congo': 'COG',
    'Central African Republic': 'CAF',
    'Chad': 'TCD',
    'Cameroon': 'CMR',
    'Nigeria': 'NGA',
    'Niger': 'NER',
    'Mali': 'MLI',
    'Burkina Faso': 'BFA',
    'Senegal': 'SEN',
    'Mauritania': 'MRT',
    'Gambia': 'GMB',
    'Guinea-Bissau': 'GNB',
    'Guinea': 'GIN',
    'Sierra Leone': 'SLE',
    'Liberia': 'LBR',
    'Ivory Coast': 'CIV',
    'Ghana': 'GHA',
    'Togo': 'TGO',
    'Benin': 'BEN',
    'South Africa': 'ZAF',
    'Namibia': 'NAM',
    'Botswana': 'BWA',
    'Zimbabwe': 'ZWE',
    'Zambia': 'ZMB',
    'Malawi': 'MWI',
    'Mozambique': 'MOZ',
    'Madagascar': 'MDG',
    'Mauritius': 'MUS',
    'Seychelles': 'SYC',
    'Comoros': 'COM',
    'Western Sahara': 'ESH',
    
    // Okeanija
    'Australia': 'AUS',
    'New Zealand': 'NZL',
    'Fiji': 'FJI',
    'Papua New Guinea': 'PNG',
    'Solomon Islands': 'SLB',
    'Vanuatu': 'VUT',
    'New Caledonia': 'NCL',
    'French Polynesia': 'PYF',
    'Samoa': 'WSM',
    'Tonga': 'TON',
    'Cook Islands': 'COK',
    'Palau': 'PLW',
    'Marshall Islands': 'MHL',
    'Micronesia': 'FSM',
    'Nauru': 'NRU',
    'Kiribati': 'KIR',
    'Tuvalu': 'TUV',
    
    // Ostalo
    'Antarctica': 'ATA',
    'Greenland': 'GRL',
    'Falkland Islands': 'FLK',
    'Gibraltar': 'GIB'
};

// Funkcija za dobijanje ISO koda države
export function getCountryCode(properties) {
    const name = properties.name || properties.NAME_EN || properties.ADMIN || properties.NAME_LONG || properties.SOVEREIGNT || 'Unknown';
    console.log('getCountryCode called with name:', name);
    
    const isoCode = countryMapping[name] || 'UNK';
    console.log('Mapped', name, 'to', isoCode);
    
    return isoCode;
}

// Funkcija za dobijanje imena države
export function getCountryName(properties) {
    return properties.name || properties.NAME_EN || properties.ADMIN || properties.NAME_LONG || properties.SOVEREIGNT || 'Unknown';
}
