[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(self)"
    # ➜ DODANO: tailwind CDN + Google Fonts
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; font-src 'self' data: https://fonts.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' https://js.stripe.com https://cdn.tailwindcss.com; connect-src 'self' https://*.supabase.co; frame-src https://js.stripe.com https://checkout.stripe.com; frame-ancestors 'self'"
